export const LANGUAGE = 'LANGUAGE';
export const DEFAULT = 'DEFAULT';
export const EN = 'en';
export const RU = 'ru';
export const REPOSITORY = 'https://github.com/LevapVeeskela/testing-task';
export const SPECIFICATION = 'https://github.com/LevapVeeskela/testing-task/blob/master/testing.pdf';
export const FORM_DATA = 'FORM_DATA';
export const MY_LINKEDIN = 'https://linkedin.com/in/veeskela';
export const MY_PHOTO_LINKEDIN = 'https://media-exp1.licdn.com/dms/image/C4D03AQFMgxspOjWR4A/profile-displayphoto-shrink_800_800/0/1548685824288?e=1669248000&v=beta&t=E199DxPAknZ4SgdmkcbkcyXB-Zd6sMvMaJ7V-QxicfA';
